### ISSUE TITLE
Please include tests in the crate

### ISSUE THREAD

**Issue by michel-slm** [mbrubeck/tree_magic#17]
Tests are not currently included in the crate; this means when packaging `tree_magic_mini` in distributions we can't verify that it works correctly or not

**Comment by mbrubeck** [comment]
The test suite for this crate is too large to publish on crates.io (and I hope to make it even larger in the future).

I suggest importing it from the git repo instead as part of your packaging process.  I apologize for the inconvenience, but I’d rather require a little extra work for the minority who actually run the tests, than force everyone who builds any crate that depends on `tree_magic_mini` to download the test suite.

**Comment by mbrubeck** [comment]
Source tarballs with tests included are available at https://github.com/mbrubeck/tree_magic/releases
