### ISSUE TITLE
missing support for image/heif if feature `with-gpl-data` is used

### ISSUE THREAD

**Issue by braeutigamj** [mbrubeck/tree_magic#26]
I created a a small test at a fork: https://github.com/mbrubeck/tree_magic/commit/a27b46a3c43d22ad2d9bd8903def56cb06ed5906

`$ cargo test` works fine
`$ cargo test -F with-gpl-data` fails:
```
---- from_u8::image_heic stdout ----
thread 'from_u8::image_heic' panicked at tests/from_u8.rs:13:9:
assertion `left == right` failed
  left: "application/octet-stream"
 right: "image/heif"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Do you have to update `magic_db`? How is it possible?

Thanks in advance

Best regards
Jonas

**Comment by mbrubeck** [comment]
Thanks for the report and test case!  Fixed in `tree_magic_db` version 3.0.1 by updating the XDG mime data files.
