### ISSUE TITLE
Add macOS path to magic files

### ISSUE THREAD

**Issue by egrieco** [mbrubeck/tree_magic#8]
I'm getting the following error: `'No MIME magic files found in the XDG default paths'`

While tree_magic searches the following paths:

```
"/usr/share/mime/magic",
"/usr/local/share/mime/magic",
"$HOME/.local/share/mime/magic",
```

On macOS 11.6 (Build 20G165), the files in question are stored at: `/usr/share/file/magic`

**Comment by mbrubeck** [comment]
The files at `/usr/share/file/magic` are not in the “Shared MIME-info Database” format expected by this crate.
